import type { components as ChatComponents } from './generated/chat';
import type { components as ControlComponents } from './generated/control';

/**
 * The shapes Primer's HTTP API returns.
 *
 * Aliases over types generated from the services' OpenAPI schemas, which are
 * checked in under `schemas/` and regenerated by CI. They were hand-written
 * against `primer_contracts` until a field renamed in Python was a runtime
 * surprise in TypeScript rather than a build failure; now it is a build
 * failure.
 *
 * Named here rather than used through `components['schemas'][...]` at every
 * call site: the generated file is a mechanical translation of a document,
 * and reading it is not how anyone should learn what a library looks like.
 * These names are also the seam - if a contract is renamed upstream, this is
 * the one file that has to say so.
 */

type ControlSchemas = ControlComponents['schemas'];
type ChatSchemas = ChatComponents['schemas'];

export type IngestionStatus = ControlSchemas['IngestionStatus'];
export type LibrarySummary = ControlSchemas['LibrarySummary'];
export type DocumentSummary = ControlSchemas['DocumentSummary'];
export type DeploymentCapabilities = ControlSchemas['DeploymentCapabilities'];
export type Principal = ControlSchemas['Principal'];

export type SourceLocator = ChatSchemas['SourceLocator'];
export type Citation = ChatSchemas['Citation'];
export type MessageSummary = ChatSchemas['MessageSummary'];
export type ConversationSummary = ChatSchemas['ConversationSummary'];
export type ChatModel = ChatSchemas['ChatModel'];

/** States where nothing further will happen without the user acting. */
export const TERMINAL_STATUSES: readonly IngestionStatus[] = [
	'ready',
	'failed',
	'unsupported',
	'cancelled',
	'deleted',
];

/**
 * An RFC 9457 problem document. Every error from Primer has this shape.
 *
 * Hand-written, because it is the one shape the schemas do not describe:
 * FastAPI documents the responses a route returns on success, and Primer's
 * errors are raised rather than returned. It is asserted against the real
 * thing by the services' own tests.
 */
export interface ProblemDetail {
	code: string;
	title: string;
	status: number;
	detail: string | null;
	request_id: string | null;
}
